{
 "title": "Plausible Analytics",
 "description": "Dashboard for plausible-exporter",
 "tags": [
  "plausible",
  "analytics"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "site",
    "label": "site",
    "query": {
     "query": "label_values(plausible_visitors,site_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Visitors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "plausible_visitors{site_id=~\"$site\"}",
     "legendFormat": "{{site_id}}"
    }
   ]
  },
  {
   "title": "Visit duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "plausible_visit_duration{site_id=~\"$site\"}",
     "legendFormat": "{{site_id}}"
    }
   ]
  },
  {
   "title": "Page Views",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "plausible_pageviews{site_id=~\"$site\"}",
     "legendFormat": "{{site_id}}"
    }
   ]
  },
  {
   "title": "Bounce rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "plausible_bounce_rate{site_id=~\"$site\"}",
     "legendFormat": "{{site_id}}"
    }
   ]
  }
 ]
}